models/models.py
resources/maskinporten_clients.py

Now that we're on Python 3.9, we can use the type hinting generics [introduced there](https://docs.python.org/3/whatsnew/3.9.html#type-hinting-generics-in-standard-collections), instead of the `typing` module.

Use Python 3.9 type hinting generics

---

serverless.yaml

Fix import errors by including the `maskinporten_api` directory in the Serverless bundle.

Include `maskinporten_api` in Serverless bundle

---

maskinporten_api/util.py
resources/maskinporten_clients.py
test/resources/test_maskinporten_clients.py

Let's check for `write` permission on the `maskinporten-client` instead.

Drop dedicated `maskinporten-key` resource type

---

maskinporten_api/maskinporten_client.py
resources/maskinporten_clients.py
test/resources/conftest.py
test/resources/test_maskinporten_clients.py

Roll back newly created Maskinporten clients when the call to create new permissions with the permission API fails.

T#168 Roll back MP client on permission API fail

---

maskinporten_api/ssm.py
models/models.py
resources/maskinporten_clients.py
test/maskinporten_api/test_ssm.py
test/resources/test_maskinporten_clients.py

Return newly created keys back to the client if no destination AWS account is given.

T#145 Add option for returning keys to the client

---

maskinporten_api/ssm.py
resources/authorizer.py
resources/maskinporten_clients.py
test/maskinporten_api/test_ssm.py
test/resources/test_maskinporten_clients.py

Make the key creation procedure more robust by changing the flow from:
1) Assume AWS role *and* write parameters to SSM.
2) Create key in Maskinporten.
To:
1) Assume AWS role (first, since it's most likely to fail).
2) Create key in Maskinporten. If this fails, no harm done.
3) Write parameters to SSM. Delete the key again from Maskinporten if that fails somehow.

T#170 Retract new keys on secrets injection error

---

maskinporten_api/ssm.py
models/models.py
test/maskinporten_api/test_ssm.py

Add `ForeignAccountSecretsClient.delete_secrets` for deleting other teams' SSM secrets.

T#173 Add `delete_secrets` method

---

maskinporten_api/maskinporten_client.py
models/models.py
resources/maskinporten.py
test/maskinporten_api/test_maskinporten_client.py
test/resources/conftest.py
test/resources/test_maskinporten.py

Construct client names in the client creation endpoint instead of outsourcing it to the API user.

T#182 Insource client name construction

---

maskinporten_api/audit.py
resources/maskinporten.py
test/resources/conftest.py
test/resources/test_maskinporten.py

Key IDs are no longer unique. Log key additions and deletions as modification on the client instead.

Fix client key audit trails

---

models/__init__.py
models/models.py
resources/maskinporten.py
test/resources/test_maskinporten.py

Optionally clean out the key secrets in SSM belonging to a client when it's deleted.

T#173 Optionally clean SSM when deleting client

---

maskinporten_api/permissions.py

Don't read `OKDATA_PERMISSION_API_URL` from the OS environment at load time in `maskinporten_api.permissions`. Read it at run time instead to make the module more flexible by not requiring the variable to be set prior to importing the module.

T#262 Don't read OS environment at load time

---

requirements.txt
setup.py

Require python-keycloak 1.x to fix 48 warnings during test runs.

Bump python-keycloak

---

doc/index.md
jobs/backup.py
serverless.yaml

Generalize the S3 backup job to include the key rotation table as well.

T#282 Back up key rotation table to S3 too

---

jobs/client_report.py
maskinporten_api/audit.py
maskinporten_api/permissions.py
resources/maskinporten.py
test/resources/conftest.py
test/resources/test_maskinporten.py

Drop the `Type` and `Env` fields; these are now baked into the `Id` field together with the client ID in order to make it unique across environments.
Depends on https://github.com/oslokommune/dataplatform-config/pull/181.

T#291 Change audit logging format

---

maskinporten_api/permissions.py
resources/maskinporten.py
test/resources/conftest.py
test/resources/test_maskinporten.py

The `get_team` endpoint no longer responds with 403 when the caller isn't a member of the team, but includes the membership status in the response payload instead.
Depends on https://github.com/oslokommune/okdata-permission-api/pull/57.

T#293 Check membership in `get_team` response

---

models/models.py
resources/maskinporten.py
test/resources/conftest.py
test/resources/test_maskinporten.py

Respond with the real key expiration times from the key listing endpoint.
Keys are no longer renewed when the `jwks` object is updated, so we can't simply count on them expiring a year from the last update time.

T#305 Respond with real key expiration times

---

maskinporten_api/ssm.py
resources/maskinporten.py
test/resources/test_maskinporten.py

Write secrets to a single JSON string in SSM instead of writing SSM secrets to individual paths. This reduces the number of calls users have to make to retrieve the necessary key data, plus that it removes the risk that details for different keys are read mid-rotation.

Make key writes to SSM atomic

---

resources/maskinporten.py
test/resources/test_maskinporten.py

Change the action path for deleting clients from `DELETE /{env}/{client_id}` to `POST /{env}/{client_id}/delete`.
Including a body in DELETE actions seems kind of discouraged, and isn't supported at all in some HTTP clients, so change it to a POST action instead.
The old endpoint is kept for a while to retain backwards compatibility.

Change client delete action path

---

maskinporten_api/ssm.py
test/maskinporten_api/test_ssm.py

Include the key expiration time in the key data JSON blob that is sent to SSM.

Include key expiration time in SSM JSON blob

---

package-lock.json
package.json
serverless.yaml

Upgrade Serverless and related plugins in order to support Python 3.11.

Upgrade Serverless for Python 3.11 support

---

jobs/client_report.py
maskinporten_api/audit.py
maskinporten_api/maskinporten_client.py
maskinporten_api/ssm.py
requirements.txt
resources/authorizer.py
serverless.yaml
setup.py
test/conftest.py
test/maskinporten_api/test_ssm.py
test/resources/test_maskinporten.py
tox.ini

Don't hardcode the email API key and the Slack webhook URL in the Lambda environment, fetch them from SSM at runtime instead.

Read secrets at runtime

---

Dockerfile
package-lock.json
package.json
requirements.txt
serverless.yaml
setup.py

Use a custom Docker image for the Lambda functions instead of the Python runtimes provided by AWS.
This will make it easier when adding new dependencies later, such as the `cryptography` library which is a hassle to run on the native Lambda images.

Dockerify Lambda runtimes

---

maskinporten_api/keys.py
maskinporten_api/maskinporten_client.py
test/maskinporten_api/test_keys.py
test/resources/conftest.py
test/resources/test_maskinporten.py

Digdir launched a new version of the Maskinporten API at 2025-05-22.
The notable changes for us are:
- New base URLs: https://api.test.samarbeid.digdir.no/api/v1/clients and https://api.samarbeid.digdir.no/api/v1/clients versus the old https://api.test.samarbeid.digdir.no/clients/ and
https://api.samarbeid.digdir.no/clients/ (note that the trailing slash is gone).
- A `sig` field is required in the client key JWT payloads. Existing keys don't have this field, so it has to be patched in whenever we update existing keys.

Update to 2025-05-22 version of Digdir's API

---

maskinporten_api/maskinporten_client.py

Token lifetime parameters with value 0 would previously give us default values when creating ID-Porten clients.
Digdir has apparently changed the API to respond to 0 values with 400 Bad Request instead. By dropping the parameters altogether, we get default lifetime values again for new clients.

Drop lifetime parameters for ID-Porten clients

---

.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml
.github/workflows/pr-tests.yml
Dockerfile
pyproject.toml
requirements.txt
setup.py
tox.ini

Upgrade the Lambda runtime to Python 3.13.
Also upgrade dependencies to get rid of known vulnerabilities.

Upgrade to Python 3.13 + dependencies

---

jobs/client_report.py

Add `__eq__` to the `TeamMissingEmailWarning` class to remove a warning from CodeQL (about `__hash__` being defined but not `__eq__`).

Define `TeamMissingEmailWarning.__eq__`
